### ISSUE TITLE
Wrong target port in docker-compose example

### ISSUE THREAD

**Issue by Avi0n** [terafin/nextdns-proxy#2]
```
    ports:
      - "53:53/udp"
```
should be 
```
    ports:
      - "53:8053/udp"
```
unless I'm missing something

**Comment by terafin** [comment]
@avion540 sorry I missed this - thanks for checking on this!

It is the correct port however, this image uses a custom local DNS port in case you want to use this in host network mode (and they don't fight for port 53) 

Note in run.sh this custom parameter:
`NEXTDNS_ARGUMENTS="-listen :8053 -report-client-info -log-queries"`
